#!/bin/sh -e

files download "https://github.com/kserve/kserve/releases/download/$KSERVE_VERSION/kserve.yaml" "core/kserve.yaml"
files download "https://github.com/kserve/kserve/releases/download/$KSERVE_VERSION/kserve-runtimes.yaml" "core/kserve-runtimes.yaml"
files download "https://github.com/kserve/kserve/releases/download/$KSERVE_VERSION/kserve_kubeflow.yaml" "core/kserve_kubeflow.yaml"

if test -z "$(kubectl api-resources --api-group=cert-manager.io -o name)"; then
    echo "Looks like cert nanager has not been installed"
    echo "Removing cert-manager custom resources from kustomization files"
    kustomize edit add patch --path no-certs/issuer.yaml
    kustomize edit add patch --path no-certs/certificate.yaml
fi
