apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-serving

resources:
- kustomize/serving-core.yaml
- kustomize/net-istio.yaml
- istio/peer-auth.yaml
- kustomize/serving-hpa.yaml
