#!/bin/bash -e

if test "$ISTIO_ENABLED" = 'enabled'; then
    kubectl label namespace "$NAMESPACE" 'istio-injection=enabled'
    kustomize edit add resource 'istio'
    cp -v kustomize/net-istio.yaml istio
fi

if test "$HPA_ENABLED" = 'enabled'; then
    kustomize edit add resource 'kustomize/serving-hpa.yaml'
fi
