apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

bases:
- kustomize/default

namespace: "kserve"

patchesJson6902:
- target:
    version: v1
    kind: Secret
    name: storage-config
  patch: |-
    - op: replace
      path: /stringData/localMinIO
      value: |-
        {
          "type": "s3",
          "access_key_id": "39ba1c2258764a6bbb60ca786e6010c6",
          "secret_access_key": "9c70abba6851445485909ae02a88acbd",
          "endpoint_url": "http://minio.kubeflow-data.svc:9000",
          "default_bucket": "mlpipelines",
          "region": "us-east-1"
        }
- target:
    version: v1
    kind: Secret
    name: modelmesh-serving
  patch: |-
    - op: replace
      path: /stringData/etcd_connection
      value: |
        {
          "endpoints": "http://etcd.kubeflow-data:2379",
          "root_prefix": "modelmesh-serving"
        }
