apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

bases:
- kustomize/default

namespace: "kserve"

patchesJson6902:
- target:
    version: v1
    kind: Secret
    name: storage-config
  patch: |-
    - op: replace
      path: /stringData/localMinIO
      value: |-
        {
          "type": "s3",
          "access_key_id": "281f9c3f159849b3abe1d29a9950adb3",
          "secret_access_key": "f2ad7fd953904f88a1f96ef013c780db",
          "endpoint_url": "http://minio.kubeflow-data.svc:9000",
          "default_bucket": "mlpipelines",
          "region": "us-east-1"
        }
- target:
    version: v1
    kind: Secret
    name: modelmesh-serving
  patch: |-
    - op: replace
      path: /stringData/etcd_connection
      value: |
        {
          "endpoints": "http://etcd.kubeflow-data:2379",
          "root_prefix": "modelmesh-serving"
        }
