#!/bin/sh -e

NAMESPACE="${NAMESPACE:-kubeflow}"

if ! kubectl -n "$NAMESPACE" get secret "katib-webhook-cert" > /dev/null; then
    echo "Generating self-signed certifiate"
    mkdir -p ".generated"
    bin/self-signed-ca.sh \
        --namespace "$NAMESPACE" \
        --service "katib-controller" \
        --output-dir ".generated" \
        --secret-name "katib-webhook-cert"
fi
