apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kserve
data:
  ingress: |-
    {
      "ingressGateway" : "knative-serving/knative-ingress-gateway",
      "ingressService" : "kserve-ingressgateway.istio-system.svc.cluster.local",
      "localGateway" : "knative-serving/knative-local-gateway",
      "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
      "ingressDomain"  : "inference.localhost",
      "ingressClassName" : "istio",
      "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
      "urlScheme": "http",
      "disableIstioVirtualHost": false
    }
