#!/bin/sh -e
verb="$(basename "$0")"

(
  cd "notebook-controller"
  HUB_KUSTOMIZE_TARBALL_SUBPATH="apps/jupyter/jupyter-web-app/upstream" \
  hub ext component kustomize "$verb"
)

(
  cd "jupyter-web-app"
  HUB_KUSTOMIZE_TARBALL_SUBPATH="apps/jupyter/notebook-controller/upstream" \
  hub ext component kustomize "$verb"
)
