apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- kustomize/overlays/kubeflow

configMapGenerator:
- name: config
  behavior: merge
  literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
