#!/bin/sh -xe
../../bin/shell/download-manifests -o "$(pwd)/bootstrap/kustomize" -s "admission-webhook/bootstrap"
../../bin/shell/download-manifests -o "$(pwd)/webhook/kustomize"   -s "admission-webhook/webhook"

kubectl="kubectl --namespace=$NAMESPACE --context=$DOMAIN_NAME"

if ! $kubectl get crd "poddefaults.kubeflow.org" -o name; then
    $kubectl create -f crds/poddefaults.yaml
fi

kustomize build "bootstrap" | $kubectl apply -f -
kustomize build "webhook"   | $kubectl apply -f -
