#!/bin/sh -xe
files download-tar "$URL" "bootstrap/kustomize" --tar-subpath "admission-webhook/bootstrap"
files download-tar "$URL" "webhook/kustomize" --tar-subpath "admission-webhook/webhook"

kubectl="kubectl --namespace=$NAMESPACE --context=$DOMAIN_NAME"

if ! $kubectl get crd "poddefaults.kubeflow.org" -o name; then
    $kubectl create -f crds/poddefaults.yaml
fi

$kubectl apply -k "bootstrap"
$kubectl apply -k "webhook"
