#!/bin/sh -xe
files download-tar "$URL" "bootstrap/kustomize" --tar-subpath "admission-webhook/bootstrap"
files download-tar "$URL" "webhook/kustomize" --tar-subpath "admission-webhook/webhook"

kubectl="kubectl --namespace=$NAMESPACE --context=$DOMAIN_NAME"

$kubectl delete -k "bootstrap"
$kubectl delete -k "webhook"

if $kubectl get secret "webhook-certs" -o name; then
    $kubectl delete secret "webhook-certs"
fi
