#!/bin/sh -xe
../../bin/shell/download-manifests -o "$(pwd)/bootstrap/kustomize" -s "admission-webhook/bootstrap"
../../bin/shell/download-manifests -o "$(pwd)/webhook/kustomize"   -s "admission-webhook/webhook"

kubectl="kubectl --namespace=$NAMESPACE --context=$DOMAIN_NAME"

kustomize build "bootstrap" | $kubectl delete -f -
kustomize build "webhook"   | $kubectl delete -f -

if $kubectl get secret "webhook-certs" -o name; then
    $kubectl delete secret "webhook-certs"
fi
