apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- kustomize/knative-eventing/base
- kustomize/knative-eventing-post-install-jobs/base
- kustomize/knative-serving/overlays/gateways
- kustomize/knative-serving-post-install-jobs/base

# vars:
# - name: namespace
#   objref:
#     kind: ConfigMap
#     name: parameters
#     apiVersion: v1
#   fieldref:
#     fieldpath: metadata.namespace
