apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transformation-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}

  ports:
  - name: grpc
    port: {{ .Values.service.grpc.port }}
    targetPort: {{ .Values.service.grpc.targetPort }}
    {{- if .Values.service.grpc.nodePort }}
    nodePort: {{ .Values.service.grpc.nodePort }}
    {{- end }}

  selector:
    {{- include "transformation-service.labels" . | nindent 4 }}
