#!/bin/sh -e

kubectl="kubectl --context=$HUB_DOMAIN_NAME --namespace=$NAMESPACE"

if test -n "$INGRESS_HOSTS" && ! $kubectl get -f ingress.yaml >/dev/null 2>&1; then
  $kubectl apply -f ingress.yaml
fi
