version: 1
kind: component

requires:
- kubernetes
- helm

lifecycle:
  verbs:
  - deploy
  - undeploy
  - backup

parameters:
- name: dns.domain
  env:  HUB_DOMAIN_NAME
- name: dex.issuer
  empty: allow
- name: dex.api.endpoint
  empty: allow
- name: ingress.protocol
  value: http
- name: ingress.host
- name: argo.namespace
  value: argo
  env: NAMESPACE
- name: argo.workflowNamespace
  value: ${argo.namespace}
- name: argo.version
  value: v3.4.3
- name: argo.oidc.clientSecret
  empty: allow
- name: argo.oidc.redirectUrl
  value: ${ingress.protocol}://${ingress.host}/oauth2/callback
- name: argo.executor
  brief: Current version of Kubeflow Pipelines supports "emissary" executor only
  value: emissary

- name: helm
  parameters:
  - name: repo
    env: HELM_REPO
    value: https://argoproj.github.io/argo-helm
  - name: chart
    value: argo-workflows
    env: HELM_CHART
  - name: chartVersion
    value: 0.20.8
    env: HELM_CHART_VERSION
  - name: valuesFile
    value: values.yaml
    env: CHART_VALUES_FILE

- name: postgresql
  empty: allow
  parameters:
  - name: host
    env: POSTGRES_HOST
  - name: user
  - name: port
    value: 5432
    env: POSTGRES_PORT
  - name: password
  - name: database
    env: POSTGRES_DB

- name: bucket
  parameters:
  - name: host
  - name: port
  - name: region
  - name: accessKey
  - name: secretKey
  - name: name

- name: hub.backup.file
  empty: allow
  env: BACKUP_FILE

templates:
  files:
  - "*.template"
  - "resources/*.template"
  extra:
    - kind: go
      files: ["resources/*.gotemplate"]
