#!/bin/sh

# shellcheck disable=SC2154,SC2250
kubectl="kubectl --context=${HUB_DOMAIN_NAME} --namespace=${NAMESPACE} --ignore-not-found=true"
$kubectl delete -f "resources/bucket-creds.yaml"

$kubectl delete secret "${COMPONENT_NAME}-ca"
echo "Done!"
