#!/bin/sh

# shellcheck disable=SC2154,SC2250
kubectl="kubectl --context=${HUB_DOMAIN_NAME} --namespace=${NAMESPACE}"

$kubectl apply -f "resources/bucket-creds.yaml"

if test -n "${AZURE_STORAGE_ACCOUNT_NAME}" && test -n "${BUCKET_HOST}"; then
  echo "WARNING: Both Azure Storage Account and S3 compatible storage connection details has been discovered."
  echo "Azure Storage Account connection will be used."
fi
