#!/bin/sh

# shellcheck disable=SC2154,SC2250
kubectl="kubectl --context=${HUB_DOMAIN_NAME} --namespace=${NAMESPACE}"

$kubectl apply -f "resources/bucket-creds.yaml"

if test -n "${INGRESS_HOSTS}"; then 
  $kubectl apply -f "resources/ingress.yaml"
fi
