#!/bin/bash -e

files download "https://github.com/kserve/kserve/releases/download/$KSERVE_VERSION/kserve.yaml" "core/kserve.yaml"
files download "https://github.com/kserve/kserve/releases/download/$KSERVE_VERSION/kserve-runtimes.yaml" "core/kserve-runtimes.yaml"
