#!/bin/bash -e

if test "$DEPLOYMENT_MODE" = 'Serverless'; then
    yq -i '.patchesStrategicMerge += ["serverless/inferenceservice-config.yaml"]' kustomization.yaml
elif test "$DEPLOYMENT_MODE" = 'RawDeployment'; then
    yq -i '.patchesStrategicMerge += ["rawdeployment/inferenceservice-config.yaml"]' kustomization.yaml
else 
    >&2 echo "Error: unsupported deployment mode: $KSERVE_MODE"
    exit 1
fi
