#!/bin/sh -e

# kubectl="$(which kubectl) --context=$HUB_DOMAIN_NAME --namespace=$NAMESPACE"

# echo "Delete Dex API gRPC server and client certificate"

# $kubectl delete secret dex-grpc-server-secret
# $kubectl delete secret dex-grpc-client-secret

# echo "Done!"
