#!/bin/sh -e

SA_SUFFIX=$(echo "$DOMAIN_NAME" | cut -d "." -f1)
# Service account name must be between 6 and 30 characters (inclusive), 
# must begin with a lowercase letter, and consist of 
# lowercase alphanumeric characters that can be separated by hyphens
SA_NAME="$(echo "$HUB_COMPONENT"-"$SA_SUFFIX" | cut -c1-29| tr '[:upper:]' '[:lower:]'| tr '_' '-')x"
SA_EMAIL="$SA_NAME@$PROJECT.iam.gserviceaccount.com"

kubectl config delete-context "$DOMAIN_NAME" > /dev/null 2>&1 || echo ""
gcloud container clusters get-credentials "$NAME" --zone "$ZONE"
kubectl config rename-context "$(kubectl config current-context)" "$DOMAIN_NAME"

if gcloud iam service-accounts describe "$SA_EMAIL" --project="$PROJECT" > /dev/null; then
  if ! gcloud iam service-accounts delete "$SA_EMAIL" --project="$PROJECT" --quiet; then 
    cat << EOF | color warn
Warning: couldn't delete service account $SA_EMAIL
We may just left some garbage in $PROJECT project
EOF
  fi
else
  echo "Service account $SA_EMAIL has not been found (mogin on)"
fi

kubectl="kubectl --context=$DOMAIN_NAME"
if $kubectl get -f "issuer-le-gcp.yaml" -o "name" 2>/dev/null; then
  $kubectl delete -f "issuer-le-gcp.yaml"
fi
